<?php 

namespace Veloz\Core;

use Veloz\Core\Router;
use Veloz\Web\Request;

class PageCaching
{
    public static function cache_app($root): void
    {
        $app_root = $root . $_ENV['APP_ROOT'];
        $cache_path = $app_root . 'resources/cache/pages/';
        $view_path = $app_root . 'views/';
        $routes = $app_root . 'routes/web.php';
        
        // Checks if path exists
        if (!is_dir($app_root)) {
            echoOutput('App folder not found. In: ' . $app_root, 1);
            return;
        }

        // Checks path for cache folder
        if (!is_dir($cache_path)) {
            echoOutput('Cache folder not found. In: ' . $cache_path, 1);
            echoOutput('Creating cache folder...', 1);
            mkdir($cache_path, 0777, true);
        }

        // Checks all folders and if they exist
        if (!is_dir($view_path)) {
            echoOutput('Views folder not found. In: ' . $view_path, 1);
            return;
        }

        // Checks if routes file exists
        if (!is_file($routes)) {
            echoOutput('Routes file not found. In: ' . $routes, 1);
            return;
        }

        $router = new Router();
        require_once $routes;

        $routes = $router->getRoutes();

        $get_routes = [];

        foreach ($routes as $route) {
            if ($route['method'] === 'GET') {
                array_push($get_routes, $route);
            }
        }

        $htaccess_data = [
            'RewriteEngine On',
            'RewriteBase /',
            'RewriteCond %{REQUEST_FILENAME} !-f',
            'RewriteCond %{REQUEST_FILENAME} !-d',
        ];

        $user_agent = 'Veloz/Caching';

        foreach ($get_routes as $get_route) {
            echoOutput('Caching route: ' . $_ENV['APP_URL'] . $get_route['filtered'], 1);

            // Tries sending an HTTP request to the first route
            $request = Request::send([
                'url' => $_ENV['APP_URL'] . $get_route['filtered'],
                'method' => 'GET',
                'headers' => [
                    'User-Agent' => $user_agent,
                ],
            ]);

            $url = $get_route['url'] ?? '';

            if (!$request) {
                echoOutput('Failed to send request to', 1);
                return;
            }

            $response = Request::get_response();

            $html = $response['data'];

            // Get current timestamp
            $timestamp = time();
            $hash = md5($get_route['filtered']);
    
            $filename = $cache_path . $hash . '.html';

            // Create the file
            file_put_contents($filename, $html);

            // Removes the first slash if it exists
            $htaccess_route = ltrim($get_route['filtered'], '/');

            // Add the route to the htaccess file
            array_push($htaccess_data, 'RewriteRule ^' . $htaccess_route . '$ ' . $_ENV['APP_ROOT'] . 'resources/cache/pages/' . $hash . '.html [L]');

            echoOutput('Cached route: ' . $_ENV['APP_URL'] . $get_route['filtered'], 1);
        }

        // Add the last line to the top of the htaccess file
        array_unshift($htaccess_data, '# Generated by Veloz/Caching on ' . date('Y-m-d H:i:s'));

        $htaccess_location = server_root() . '.htaccess';

        // Gets current htaccess data
        $current_htaccess_data = file_get_contents($htaccess_location);

        // Combines the current htaccess data with the new data
        $htaccess_data = array_merge($htaccess_data, explode("\n", $current_htaccess_data));

        // Write the htaccess file
        file_put_contents(server_root() . '.htaccess', implode("\n", $htaccess_data));

        echoOutput('Saved routes to .htaccess file.', 1, 1);
    }
}
    